name: Test

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run audit
        run: npm run test:audit

      - name: Prettier
        run: npm run test:format

      - name: ESLint
        run: npm run lint

      - name: Types
        run: npm run test:types

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
